import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { IDocument } from '../models/Document';

/**
 * Generates a simple A4 PDF document for the given HMS document record.
 * Returns a Buffer containing the PDF bytes.
 */
export async function generateDocumentPdf(doc: IDocument): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4

  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const { width, height } = page.getSize();
  const margin = 50;
  let y = height - margin;

  // Header
  page.drawText('MEDICORE HOSPITAL MANAGEMENT SYSTEM', {
    x: margin,
    y,
    size: 14,
    font: boldFont,
    color: rgb(0, 0.3, 0.6),
  });

  y -= 25;
  page.drawLine({
    start: { x: margin, y },
    end: { x: width - margin, y },
    thickness: 1,
    color: rgb(0, 0.3, 0.6),
  });

  y -= 30;

  // Document type
  const formattedType = doc.type
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  page.drawText(`Document Type: ${formattedType}`, {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });

  y -= 20;

  // Document ID
  page.drawText(`Document ID: ${doc.documentId}`, {
    x: margin,
    y,
    size: 11,
    font: regularFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  y -= 18;

  // Patient ID
  page.drawText(`Patient ID: ${doc.patientId.toString()}`, {
    x: margin,
    y,
    size: 11,
    font: regularFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  y -= 18;

  // Doctor ID
  page.drawText(`Issued By (Doctor ID): ${doc.issuedBy.toString()}`, {
    x: margin,
    y,
    size: 11,
    font: regularFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  y -= 25;

  // Template data
  if (doc.templateData && Object.keys(doc.templateData).length > 0) {
    page.drawText('Template Data:', {
      x: margin,
      y,
      size: 11,
      font: boldFont,
      color: rgb(0, 0, 0),
    });
    y -= 18;

    for (const [key, value] of Object.entries(doc.templateData)) {
      const line = `  ${key}: ${String(value)}`;
      page.drawText(line, {
        x: margin,
        y,
        size: 10,
        font: regularFont,
        color: rgb(0.2, 0.2, 0.2),
      });
      y -= 16;

      if (y < margin + 60) break; // safety: don't overflow page
    }
  }

  y -= 10;

  // Notes
  if (doc.notes) {
    page.drawText('Notes:', {
      x: margin,
      y,
      size: 11,
      font: boldFont,
      color: rgb(0, 0, 0),
    });
    y -= 18;

    page.drawText(doc.notes.substring(0, 200), {
      x: margin,
      y,
      size: 10,
      font: regularFont,
      color: rgb(0.2, 0.2, 0.2),
    });
    y -= 18;
  }

  y -= 10;

  // Issue date
  const issueDateStr = doc.issuedAt
    ? doc.issuedAt.toISOString().split('T')[0]
    : new Date().toISOString().split('T')[0];

  page.drawText(`Issue Date: ${issueDateStr}`, {
    x: margin,
    y,
    size: 11,
    font: regularFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  // Footer
  page.drawLine({
    start: { x: margin, y: margin + 20 },
    end: { x: width - margin, y: margin + 20 },
    thickness: 0.5,
    color: rgb(0.5, 0.5, 0.5),
  });

  page.drawText('Generated by HMS', {
    x: margin,
    y: margin + 5,
    size: 9,
    font: regularFont,
    color: rgb(0.5, 0.5, 0.5),
  });

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}
